### ISSUE TITLE
[Variable name] Follow Unity's name for exposed variables

### ISSUE THREAD

**Issue by Kirbyrawr** [Phong13/BulletSharpUnity3d#9]

**Comment by Kirbyrawr** [comment]
I think we should change the name of the variables to follow the unity's name of the components.
Example:

Unity:
`BoxCollider collider;
collider.size = Vector3.one;`

Bullet:
`BBoxShape collider;
collider.extents = Vector3.one;`

The thing i want:
`BBoxShape collider;
collider.size = Vector3.one;`

**Comment by Phong13** [comment]
Thanks for the suggestion. I agree that we should do this for variables of classes in the "BulletUnity" folder. 

However I don't want to change the variable names in the "Plugins/BulletSharp" folder. The reason is that the bulletsharp classes are a fork of the https://github.com/AndresTraks/BulletSharpPInvoke project. We regularly pull code from the upstream branch (about once a month). It is much easier if we have not changed the names of the variables in those classes.

**Comment by Kirbyrawr** [comment]
Fair enough!
